# Generated by Django 3.2.6 on 2021-11-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
