# Generated by Django 3.2.6 on 2021-11-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211130_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['date_added']},
        ),
    ]
